name: Flutter Core Event Source
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/flutter_core_event_source_verify_and_test.yaml'
      - 'packages/flutter_core_event_source/**'

  push:
    branches:
      - master
      - main
    paths:
      - '.github/workflows/**'
      - 'packages/flutter_core_event_source/**'


jobs:
  verify_and_test:
    runs-on: self-hosted
    env:
      FIREBASE_EMULATORS_PATH: ${{ github.workspace }}/emulator-cache

    steps:
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          path: ${{ env.FIREBASE_EMULATORS_PATH }}
          key:
            ${{ runner.os }}-firebase-emulators-${{
            hashFiles('emulator-cache/**') }}
        continue-on-error: true
      - uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
        with:
          working_directory: packages/flutter_core_event_source
          min_coverage: 90
          flutter_channel: stable
          flutter_version: 3.7.7
