name: Spell Check

on:
  pull_request:
    branches:
      - master
      - main
  push:
    branches:
      - master
      - main

jobs:
  spell_check:
    uses: ./.github/workflows/spell_check.yml
    with:
      config: .github/cspell.json
